manifest_version = 1

[module]
name = "Platform Converter"
id = "platform_converter"
description = "Get versions of tracks and videos from different platforms"
version = "4.1.2"
license = "GNU GPLv3"
authors = ["Fripe"]
requirements = [
    "aiohttp",
    "youtube-search-python"
]
